name: Tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run Jest With Coverage
      uses: ChristiaanScheermeijer/jest-reporter-action@v0.4.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "./node_modules/.bin/jest --coverage"
